[versions]
minecraft = "1.19.2"
parchment_minecraft = "1.19.2"
parchment_mappings = "2022.08.14"
quilt_loader = "0.17.4"

qsl = "3.0.0-beta.14+1.19.2"
groovyduvet = "1.1.0"
cgl = "0.1.0"

gml = "1.1.3"

groovy = "4.0.4"
autoservice = "1.0.1"

forge = "1.19.2-43.1.15"
forgegradle = "5.1.+"
librarian = "1.+"
mixin = "0.8.5"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

qsl = { module = "org.quiltmc:qsl", version.ref = "qsl" }
groovyduvet_all = { module = "io.github.lukebemish.groovyduvet:groovyduvet", version.ref = "groovyduvet" }
groovyduvet_groovy = { module = "io.github.lukebemish.groovyduvet:groovyduvet-groovy", version.ref = "groovyduvet" }
cgl_common = { module = "io.github.groovymc.cgl:cgl-1.19.2", version.ref = "cgl" }
cgl_forge = { module = "io.github.groovymc.cgl:cgl-1.19.2-forge", version.ref = "cgl" }
cgl_quilt = { module = "io.github.groovymc.cgl:cgl-1.19.2-quilt", version.ref = "cgl" }

gml = { module = "com.matyrobbrt.gml:gml", version.ref = "gml" }

groovy = { module = "org.apache.groovy:groovy", version.ref = "groovy" }
autoservice = { module = "com.google.auto.service:auto-service", version.ref = "autoservice" }

forge = { module = "net.minecraftforge:forge", version.ref = "forge" }
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin"}

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "0.12.+" }
forgegradle = {id = "net.minecraftforge.gradle", version.ref = "forgegradle"}
librarian = {id = "org.parchmentmc.librarian.forgegradle", version.ref = "librarian"}
